on:
  push:
    paths:
      - "terraform/*"
    branches:
      - "main"
env:
  TF_VAR_project_id: ${{secrets.TF_VAR_PROJECT_ID}}
  TF_VAR_region: ${{secrets.TF_VAR_REGION}}
  TF_VERSION: 'latest'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: 'Terraform Init'
        run: terraform init
      - name: 'Terraform Validate'
        run: terraform validate
      # - name: 'Terraform Plan'
      #   run: terraform plan
      # - name: 'Terraform Apply'
      #   run: terraform apply -auto-approve